apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-shop-service
spec:
  replicas: 1  # Adjust the number of replicas based on your needs
  selector:
    matchLabels:
      app: coffee-shop-service
  template:
    metadata:
      labels:
        app: coffee-shop-service
    spec:
      containers:
        - name: coffee-shop-service
          image: medtest2013/coffeeshop # Replace with your actual image
          ports:
            - containerPort: 8081  # Updated to match the application's configured port
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-service:8761/eureka  # Assuming you're using Eureka for service discovery
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-shop-service
spec:
  type: LoadBalancer  # Use ClusterIP if you don't need external access
  ports:
    - port: 8081
      targetPort: 8081  # Updated to forward traffic to the container's port 8081
  selector:
    app: coffee-shop-service
