apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeshop-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffeeshop
  template:
    metadata:
      labels:
        app: coffeeshop
    spec:
      containers:
        - name: coffeeshop
          image: medtest2013/coffeeshop:latest
          ports:
            - containerPort: 8080
